### PR TITLE
add cuda Free on empty framework (with vim)

### PR DESCRIPTION
**Pull request by shrekshao**
Lured by Patrick.........  I want a shirt........ -_-!!!!

Add a cudaFree() to free the device memories. Modify with vim on Linux. So there should be no tab this time.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Looks good!  @kainino0x can merge if he agrees.

What size are you? :)

**Comment by shrekshao** [comment]
medium.... haha... tiny contribution after all.

**Comment by pjcozzi** [comment]
See me before class on **Tuesday**.  I will try to remember to bring a shirt - a Cesium one, I am out of Vulkan shirts.

**Comment by kainino0x** [comment]
@shrekshao Your change looks good by itself - but notice that your pull request includes a commit which has your own work for the project!

Fixing this requires a bit of git magic - you'll need to create a branch in your repository that is equivalent to our `master` branch (`git checkout -b fix-cudaFree ee98cfc`), then add your change on top of it. In order

Would you mind doing that and opening it as a new pull request? Thanks for your contribution!

EDIT: changed ref to one that you'll have

**Comment by shrekshao** [comment]
ah... that commit is there because I commit a rebase one with some of my
changes. But the pull request I sent is actually free of my code. I did
create a branch.
But never mind, I will try to follow your instruction to send a clean one

**Pull request closed without merging**
